import { BASE_URL, URL_PART } from "./route";

export const CLIENT_ROUTES = {
  REFRESH_TOKEN: `${BASE_URL.CLIENT}/refresh-token`,
  REFRESH_SESSION: `${BASE_URL.CLIENT}/refresh-session`,
  SAVE_FCM_TOKEN: `${BASE_URL.CLIENT}/save-fcm-token`,
  NOTIFICATIONS: `${BASE_URL.CLIENT}/notifications`,
  MARK_NOTIFICATION_READ: `${BASE_URL.CLIENT}/notifications/read`,
  SEND_OTP: `${BASE_URL.CLIENT}/send-otp`,
  SIGNUP: `${BASE_URL.CLIENT}/signup`,
  LOGIN: `${BASE_URL.CLIENT}/login`,
  GOOGLE_AUTH: `${BASE_URL.CLIENT}/google-auth`,
  FORGOT_PASSWORD: `${BASE_URL.CLIENT}/forgot-password`,
  RESET_PASSWORD: `${BASE_URL.CLIENT}/reset-password`,
  CATEGORIES: `${BASE_URL.CLIENT}/categories`,
  DETAILS: `${BASE_URL.CLIENT}/details`,
  CHANGE_PASSWORD: `${BASE_URL.CLIENT}/change-password`,
  SERVICES: `${BASE_URL.CLIENT}/services`,
  SERVICE_BY_ID: (id: string) => `${BASE_URL.CLIENT}/services/${id}`,
  BOOK_SERVICE: (id: string) => `${BASE_URL.CLIENT}/services/${id}/book`,
  RESCHEDULE_BOOKING: (bookingId: string) => `${BASE_URL.CLIENT}/bookings/${bookingId}/reschedule`,
  BOOKINGS: `${BASE_URL.CLIENT}/bookings`,
  CREATE_BOOKING_PAYMENT: `${BASE_URL.CLIENT}/create-booking-payment`,
  CONFIRM_PAYMENT: `${BASE_URL.CLIENT}/confirm-payment`,
  CANCEL_BOOKING: (bookingId: string) => `${BASE_URL.CLIENT}/cancel-booking/${bookingId}`,
  EVENTS: `${BASE_URL.CLIENT}/events`,
  NEARBY_EVENTS: `${URL_PART.client}/nearby`,
  EVENT_BY_ID: (eventId: string) => `${BASE_URL.CLIENT}/events/${eventId}`,
  CHECK_EVENT_BOOKING: (id: string) => `${BASE_URL.CLIENT}/events/${id}/check-booking`,
  CREATE_TICKET: `${BASE_URL.CLIENT}/create-ticket`,
  CONFIRM_TICKET_PAYMENT: `${BASE_URL.CLIENT}/confirm-ticket-payment`,
  TICKETS: `${BASE_URL.CLIENT}/tickets`,
  CANCEL_TICKET: (ticketId: string) => `${BASE_URL.CLIENT}/cancel-ticket/${ticketId}`,
  WALLET: `${BASE_URL.CLIENT}/wallet`,
  REVIEW: `${BASE_URL.CLIENT}/review`,
  REVIEWS: `${BASE_URL.CLIENT}/reviews`,
  WORK_SAMPLES_BY_VENDOR: (vendorId: string) => `${BASE_URL.CLIENT}/work-sample/${vendorId}`,
  LOGOUT: `${BASE_URL.CLIENT}/logout`,
};